version: '2'
services:
    server:
        image: linkeddatafragments/server.js
        ports:
        - "80:3000"
        volumes:
        - ./data/:/data
        - ./config.json:/tmp/config.json
        command: /tmp/config.json

